default: &default
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV.fetch("DB_HOST", "localhost") %>"
  port: "<%= ENV.fetch("DB_PORT", 5432) %>"
  username: "<%= ENV.fetch("DB_USERNAME", "postgres") %>"
  password: "<%= ENV.fetch("DB_PASSWORD", "postgres") %>"
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maneja_api_development

test:
  <<: *default
  database: maneja_api_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
